### ISSUE TITLE
Added app.covidvisual.com to list of corona apps

### ISSUE THREAD

**Issue by abuuzayr** [nikrich/za-api-covid-19#4]
Hi @nikrich ! Thank you very much for your hard work in keeping the South African public informed. Hope you and your loved ones are well, safe and healthy during these times. 

I've added your dashboard to this little list https://github.com/abuuzayr/coronavirus-apps just to showcase your app to more people. Congrats! You're the first from the RSA. 

Hope all will remain well and this will all be over soon. Stay safe!

**Comment by nikrich** [comment]
Thanks @abuuzayr ! Hope you and your loved ones are safe!
