### ISSUE TITLE
Deaths Not Updated 

### ISSUE THREAD

**Issue by XhantiMda** [nikrich/za-api-covid-19#5]
Hey Jannik, your API is lekker but the deaths have not been updated. Is there a way I can assist with keeping the data in sync with the national stats?

I think if you can get the deaths from this file it will fix the problem (covid19za_provincial_cumulative_timeline_deaths.csv)

**Comment by nikrich** [comment]
Investigating thanks X! I'm actually busy rewriting the API on Cloudflare Workers since the Google App Engine Hosting is getting expensive. Any interest in assisting? 

Apologies for only getting back to you now

**Comment by XhantiMda** [comment]
No worries.  

Yeah I'm interested, I'm available on weekends, drop the link to the link to the repo (if the project is not done yet). 
You got Skype? Lets chat there, search for Xhanti Mda

**Comment by nikrich** [comment]
@XhantiMda Skype username: live:jannik811
